steps:

# Build
- name: 'microsoft/dotnet:sdk'
  #args: [ 'build', '-c', 'Release' ]
  args: ['dotnet', 'publish','-c','Release']
  dir: 'CoreWebAPI/WebAPI/'
  
# Deploy to google cloud app egnine
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  dir: '\bin\Release\netcoreapp2.1\publish\app.yaml'
  
  
