#steps:

# Build
#- name: 'microsoft/dotnet:sdk'
#  args: [ 'build', '-c', 'Release' ]
#  dir: 'WebAPI/'

# Build
steps:
- name: 'gcr.io/$PROJECT_ID/windows-builder'
  args: [ 
          '--region', 'europe-west2',
          '--zone', 'a',
          'build', '-c', 'Release' ]
  dir: 'C:\workspace\3-Tier-App\WebAPI\WebAPI.sln'        
