version: '3.4'

services:
  api_server:
    image: ${DOCKER_REGISTRY-}api_server
    build:
      context: .\WebApplication1
      dockerfile: Dockerfile

  sql_server:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"


